title: Hamaluik Recipes
description: >-
  Recipes I've collected
domain: hamaluik.github.io
url: https://hamaluik.github.io
baseurl: /recipes/
tagline: "A personal collection of tried-and-true recipes without the fluff."

collections:
  recipes:
    output: true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

