---
label: Recipe
hide_body: false
display_field: title
fields:
- type: text
  name: layout
  label: layout
  hidden: true
  default: recipe
  config:
    required: true
- type: text
  name: title
  label: Recipe Title / Name
  config:
    required: true
- type: text
  name: description
  label: Description
  description: A short description about the recipe
- name: category
  type: select
  default: Baking
  config:
    required: true
    options:
    - Baking
    - Breakfast
    - Dinner
    - Dessert
    - Drinks
    - Other
    - Snack / Side
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
  description: What type of recipe is this?
- type: field_group
  name: source
  label: Source
  fields:
  - type: text
    name: name
    label: Name
    description: The name of the person / organisation the recipe is from.
  - type: text
    name: url
    label: URL
    description: A URL to the source of the recipe (if available)
  description: Where is this recipe from?
- type: number
  name: preptime
  label: Prep Time
  description: How long (in minutes) does it take to prepare this recipe?
- type: number
  name: cooktime
  label: Cook Time
  description: How long (in minutes) does it take to cook this recipe?
- type: number
  name: servings
  label: Servings
  description: How many servings does this recipe normally make?
- type: list
  name: ingredients
  label: Ingredients
  description: The ingredients in the recipe. Try to order them in the order they
    will be used in the instructions.
  config:
    use_select: false
    min: 1
- type: list
  name: instructions
  label: Instructions
  description: The recipe instructions!
  config:
    min: 1
pages:
- _recipes/broccoli-salad.md
- _recipes/chocolate-chip-coffee-bars-cookies.md
- _recipes/chocolate-chip-cookies.md
- _recipes/green-onion-cakes.md
- _recipes/hamburger-soup.md
- _recipes/ma-s-fresh-strawberry-cake.md
- _recipes/nova-scotia-chicken.md
- _recipes/rice-krispie-squares.md
- _recipes/stew-dunpings.md
- _recipes/tuck-shop-cinnamon-buns.md
- _recipes/ultimate-sugar-cookies.md
