---
label: Recipe
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: category
  label: category
- type: field_group
  name: source
  label: source
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: url
    label: url
- type: number
  name: preptime
  label: preptime
- type: number
  name: cooktime
  label: cooktime
- type: number
  name: servings
  label: servings
- type: list
  name: ingredients
  label: ingredients
- type: list
  name: instructions
  label: instructions
